name: PC

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download & Install LiteManager Server
        run: |
          Invoke-WebRequest -Uri "https://www.litemanager.com/soft/litemanager_5.zip" -OutFile "litemanager.zip"
          Expand-Archive -Path "litemanager.zip" -DestinationPath "LiteManager"
          Start-Process -FilePath "LiteManager/LiteManager Pro - Server.msi" -ArgumentList "/quiet /norestart" -Wait
          
          # Optional: Create basic log file
          echo "LiteManager Installed" > lm_log.txt

      - name: Download & Run Setup Script (Auto Config)
        run: |
          curl -s -L -o setup.py https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/setup.py
          python setup.py

      - name: Show LiteManager Info
        run: |
          curl -s -L -o show.bat https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/show.bat
          cmd /c show.bat

      - name: Download Extra Files
        run: |
          $desktopPath = [System.Environment]::GetFolderPath('Desktop')
          $filesFolder = "$desktopPath\Files"
          if (-not (Test-Path $filesFolder)) {
            New-Item -ItemType Directory -Path $filesFolder
          }
          $filesToDownload = @(
            "BraveSetup.exe",
            "MEGAsyncSetup64.exe",
            "DiscordSetup.exe"
          )
          $fileUrls = @{
            "BraveSetup.exe" = "https://laptop-updates.brave.com/latest/winx64";
            "MEGAsyncSetup64.exe" = "https://mega.nz/MEGAsyncSetup64.exe";
            "DiscordSetup.exe" = "https://discord.com/api/download?platform=win";
          }
          foreach ($file in $filesToDownload) {
            $filePath = "$filesFolder\$file"
            if (-not (Test-Path $filePath)) {
              $fileUrl = $fileUrls[$file]
              if ($fileUrl -ne $null) {
                Invoke-WebRequest -Uri $fileUrl -OutFile $filePath
              }
            }
          }

      - name: Install Apps (Firefox, Steam, etc.)
        run: |
          # [نفس كود تنزيل وتثبيت البرامج زي في النسخة الأصلية]

      - name: Set User Password
        run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

      - name: UI Tweaks
        run: |
          # [نفس كود تخصيص سطح المكتب وتعديل الريجيستري]

